[colors.primary]
background = "#0a1017"
foreground = "#c1c3c5"

[colors.cursor]
text = "#0a1017"
cursor = "#c1c3c5"

[colors.vi_mode_cursor]
text = "#0a1017"
cursor = "#c1c3c5"

[colors.search.matches]
foreground = "#0a1017"
background = "#c1c3c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59626d"
background = "#c1c3c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a1017"
red = "#6D6B6D"
green = "#44718A"
yellow = "#837E83"
blue = "#4C9CBE"
magenta = "#959396"
cyan = "#9EA5AE"
white = "#c1c3c5"

[colors.bright]
black = "#59626d"
red = "#6D6B6D"
green = "#44718A"
yellow = "#837E83"
blue = "#4C9CBE"
magenta = "#959396"
cyan = "#9EA5AE"
white = "#c1c3c5"

[colors.dim]
black = "#c1c3c5"
red = "#6D6B6D"
green = "#959396"
yellow = "#837E83"
blue = "#4C9CBE"
magenta = "#44718A"
cyan = "#9EA5AE"
white = "#59626d"

