[colors]
background = '#0a10178e'
black = '#0a1017'
blue = '#6D6B6D'
cursor = '#c1c3c5'
cyan = '#44718A'
foreground = '#c1c3c5'
green = '#837E83'
magenta = '#4C9CBE'
red = '#959396'
tabs = '#c1c3c5'
tabs-active = '#9EA5AE'
white = '#c1c3c5'
yellow = '#c1c3c5'
dim-black = '#0a10178e'
dim-blue = '#6D6B6D8e'
dim-cyan = '#44718A8e'
dim-foreground = '#c1c3c58e'
dim-green = '#837E838e'
dim-magenta = '#4C9CBE8e'
dim-red = '#9593968e'
dim-white = '#9EA5AE8e'
dim-yellow = '#c1c3c58e'
light-black = '#6D6B6D'
light-blue = '#44718A'
light-cyan = '#837E83'
light-foreground = '#4C9CBE'
light-green = '#959396'
light-magenta = '#9EA5AE'
light-red = '#c1c3c5'
light-white = '#6D6B6D'
light-yellow = '#44718A'
